# GENERATED by https://github.com/zmwangx/homebrew-npm-noob

require "language/node"

class Jsondiffpatch < Formula
  desc "JSON diff & patch (object and array diff, text diff, multiple output formats)"
  homepage "https://github.com/benjamine/jsondiffpatch"
  url "https://registry.npmjs.org/jsondiffpatch/-/jsondiffpatch-0.7.3.tgz"
  sha256 "e38efa0c3af8b12101cd7453bc45ffb009c36da67f681d19b096b88d9e7f85df"
  license "MIT"

  livecheck do
    url :stable
  end

  depends_on "node"

  def install
    system "npm", "install", *Language::Node.std_npm_install_args(libexec)
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    raise "Test not implemented."
  end
end
